# Usage:
#
# /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
# brew bundle --global
#

brew "clang-format"
brew "cmake"
brew "cppcheck"
brew "doxygen"
brew "ffmpeg"
brew "fzf"
brew "gcc"
brew "gifsicle"
brew "go"
brew "htop"
brew "llvm"
brew "midnight-commander"
brew "neovim"
brew "ninja"
brew "node"
brew "pass"
brew "podman"
brew "ripgrep"
brew "staticcheck"
brew "tldr"
brew "tmux"
brew "tree"
brew "universal-ctags"

cask "appcleaner"
cask "google-chrome"
cask "kitty"
cask "qbittorrent"
# cask "qt-creator"
cask "transmission"
cask "visual-studio-code"
cask "vlc"
