# Usage:
# /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
# brew bundle --global

brew "clang-format"
brew "cmake"
brew "codespell"
brew "cppcheck"
brew "doxygen"
brew "ffmpeg"
brew "fzf"
brew "gcc"
brew "gifsicle"
brew "git"
brew "htop"
brew "imhex"
brew "lcov"
brew "llvm"
brew "make"
brew "midnight-commander"
brew "ninja"
brew "nvim"
brew "pass"
brew "podman"
brew "ripgrep"
brew "tldr"
brew "tmux"
brew "tree"
brew "universal-ctags"
brew "vim"

cask "android-studio"
cask "appcleaner"
cask "cyberduck"
cask "discord"
cask "firefox"
cask "gimp"
cask "google-chrome"
cask "inkscape"
cask "kdenlive"
cask "kitty"
cask "krita"
cask "mpv"
cask "qbittorrent"
# cask "qt-creator"
cask "redream"
cask "sweet-home3d"
cask "telegram"
cask "the-unarchiver"
cask "transmission"
cask "yandex"
